/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateRideShareInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptRide"
      | "addPauser"
      | "cancelRide"
      | "completeRide"
      | "driverCounter"
      | "drivers"
      | "getActiveRideRequestsCount"
      | "getAvailableDriversCount"
      | "getDriverInfo"
      | "getDriverRideHistory"
      | "getPassengerRideHistory"
      | "getRideDetails"
      | "owner"
      | "pause"
      | "paused"
      | "pausers"
      | "protocolId"
      | "registerDriver"
      | "registeredDrivers"
      | "removePauser"
      | "requestRide"
      | "rideCounter"
      | "rideRequests"
      | "setDriverAvailability"
      | "unpause"
      | "verifyDriver"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DriverRegistered"
      | "DriverVerified"
      | "Paused"
      | "RideRequested"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptRide",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRide",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeRide",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "driverCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "drivers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveRideRequestsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableDriversCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDriverInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDriverRideHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPassengerRideHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRideDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pausers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerDriver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registeredDrivers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removePauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRide",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rideCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rideRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDriverAvailability",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyDriver",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "acceptRide", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addPauser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelRide", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeRide",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "driverCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drivers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveRideRequestsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableDriversCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDriverInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDriverRideHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPassengerRideHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRideDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pausers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDriver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredDrivers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRide",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rideCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rideRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDriverAvailability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyDriver",
    data: BytesLike
  ): Result;
}

export namespace DriverRegisteredEvent {
  export type InputTuple = [driver: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [driver: string, timestamp: bigint];
  export interface OutputObject {
    driver: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DriverVerifiedEvent {
  export type InputTuple = [driver: AddressLike];
  export type OutputTuple = [driver: string];
  export interface OutputObject {
    driver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RideRequestedEvent {
  export type InputTuple = [
    rideId: BigNumberish,
    passenger: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    rideId: bigint,
    passenger: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    rideId: bigint;
    passenger: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateRideShare extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateRideShare;
  waitForDeployment(): Promise<this>;

  interface: PrivateRideShareInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptRide: TypedContractMethod<
    [_rideId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addPauser: TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;

  cancelRide: TypedContractMethod<
    [_rideId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeRide: TypedContractMethod<
    [_rideId: BigNumberish],
    [void],
    "nonpayable"
  >;

  driverCounter: TypedContractMethod<[], [bigint], "view">;

  drivers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint] & {
        isAvailable: boolean;
        isVerified: boolean;
        totalRides: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  getActiveRideRequestsCount: TypedContractMethod<[], [bigint], "view">;

  getAvailableDriversCount: TypedContractMethod<[], [bigint], "view">;

  getDriverInfo: TypedContractMethod<
    [_driver: AddressLike],
    [
      [boolean, boolean, bigint, bigint] & {
        isAvailable: boolean;
        isVerified: boolean;
        totalRides: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  getDriverRideHistory: TypedContractMethod<
    [_driver: AddressLike],
    [bigint[]],
    "view"
  >;

  getPassengerRideHistory: TypedContractMethod<
    [_passenger: AddressLike],
    [bigint[]],
    "view"
  >;

  getRideDetails: TypedContractMethod<
    [_rideId: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        passenger: string;
        matchedDriver: string;
        requestTime: bigint;
        isActive: boolean;
        isMatched: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pausers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  registerDriver: TypedContractMethod<[], [void], "nonpayable">;

  registeredDrivers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  removePauser: TypedContractMethod<
    [_pauser: AddressLike],
    [void],
    "nonpayable"
  >;

  requestRide: TypedContractMethod<[], [void], "nonpayable">;

  rideCounter: TypedContractMethod<[], [bigint], "view">;

  rideRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        passenger: string;
        matchedDriver: string;
        requestTime: bigint;
        isActive: boolean;
        isMatched: boolean;
      }
    ],
    "view"
  >;

  setDriverAvailability: TypedContractMethod<
    [_available: boolean],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyDriver: TypedContractMethod<
    [_driver: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptRide"
  ): TypedContractMethod<[_rideId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addPauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelRide"
  ): TypedContractMethod<[_rideId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeRide"
  ): TypedContractMethod<[_rideId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "driverCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "drivers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint] & {
        isAvailable: boolean;
        isVerified: boolean;
        totalRides: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveRideRequestsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAvailableDriversCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDriverInfo"
  ): TypedContractMethod<
    [_driver: AddressLike],
    [
      [boolean, boolean, bigint, bigint] & {
        isAvailable: boolean;
        isVerified: boolean;
        totalRides: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDriverRideHistory"
  ): TypedContractMethod<[_driver: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPassengerRideHistory"
  ): TypedContractMethod<[_passenger: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRideDetails"
  ): TypedContractMethod<
    [_rideId: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        passenger: string;
        matchedDriver: string;
        requestTime: bigint;
        isActive: boolean;
        isMatched: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pausers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerDriver"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredDrivers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removePauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRide"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rideCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rideRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        passenger: string;
        matchedDriver: string;
        requestTime: bigint;
        isActive: boolean;
        isMatched: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setDriverAvailability"
  ): TypedContractMethod<[_available: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyDriver"
  ): TypedContractMethod<[_driver: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DriverRegistered"
  ): TypedContractEvent<
    DriverRegisteredEvent.InputTuple,
    DriverRegisteredEvent.OutputTuple,
    DriverRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DriverVerified"
  ): TypedContractEvent<
    DriverVerifiedEvent.InputTuple,
    DriverVerifiedEvent.OutputTuple,
    DriverVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RideRequested"
  ): TypedContractEvent<
    RideRequestedEvent.InputTuple,
    RideRequestedEvent.OutputTuple,
    RideRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DriverRegistered(address,uint256)": TypedContractEvent<
      DriverRegisteredEvent.InputTuple,
      DriverRegisteredEvent.OutputTuple,
      DriverRegisteredEvent.OutputObject
    >;
    DriverRegistered: TypedContractEvent<
      DriverRegisteredEvent.InputTuple,
      DriverRegisteredEvent.OutputTuple,
      DriverRegisteredEvent.OutputObject
    >;

    "DriverVerified(address)": TypedContractEvent<
      DriverVerifiedEvent.InputTuple,
      DriverVerifiedEvent.OutputTuple,
      DriverVerifiedEvent.OutputObject
    >;
    DriverVerified: TypedContractEvent<
      DriverVerifiedEvent.InputTuple,
      DriverVerifiedEvent.OutputTuple,
      DriverVerifiedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RideRequested(uint256,address,uint256)": TypedContractEvent<
      RideRequestedEvent.InputTuple,
      RideRequestedEvent.OutputTuple,
      RideRequestedEvent.OutputObject
    >;
    RideRequested: TypedContractEvent<
      RideRequestedEvent.InputTuple,
      RideRequestedEvent.OutputTuple,
      RideRequestedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
