codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 75%
        threshold: 10%
        base: auto

  ignore:
    - "test/**"
    - "scripts/**"
    - "tasks/**"
    - "**/*.test.ts"
    - "**/*.spec.ts"
    - "**/*.config.ts"
    - "**/*.config.js"
    - "node_modules/**"
    - ".next/**"

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true
